// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Theme() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n\t\t:root { --bg:#fff; --fg:#1a1a1a; --accent:#d64545; --border:#e3e3e3; --muted:#666; }\n\t\t[data-theme=\"dark\"]   { --bg:#121212; --fg:#e8e8e8; --accent:#ff6b6b; --border:#2a2a2a; --muted:#999; }\n\t\t[data-theme=\"cherry\"] { --bg:#fff1f1; --fg:#3a0a0a; --accent:#c53030; --border:#f0c9c9; --muted:#8a3e3e; }\n\t\t[data-theme=\"ocean\"]  { --bg:#e8f4ff; --fg:#0c1a2b; --accent:#1e6fb8; --border:#b5d6f1; --muted:#45678a; }\n\t\t[data-theme=\"gold\"]   { --bg:#fff8e6; --fg:#3a2a00; --accent:#b87f00; --border:#e8d99d; --muted:#8a6d24; }\n\t\t[data-theme=\"autumn\"] { --bg:#fff3e0; --fg:#2a1a0a; --accent:#c45618; --border:#f0cfa0; --muted:#8a5a2e; }\n\t\t[data-theme=\"winter\"] { --bg:#e6f2ff; --fg:#0a1a3a; --accent:#2a4f9c; --border:#b5c9e8; --muted:#4a6a9a; }\n\t\thtml, body { margin:0; background:var(--bg); color:var(--fg); font-family:-apple-system,Segoe UI,Roboto,sans-serif; }\n\t\t.shell { display:grid; grid-template-columns:22% 1fr 28%; min-height:100vh; }\n\t\t.shell > nav  { border-right:1px solid var(--border); padding:12px; }\n\t\t.shell > main { padding:16px; overflow:auto; }\n\t\t.shell > aside{ border-left:2px solid var(--accent); padding:12px; background:rgba(0,0,0,.02); display:none; }\n\t\t.shell > aside[data-open]{ display:block; }\n\t\t@media (max-width:900px){ .shell{ grid-template-columns:1fr; } .shell>aside[data-open]{ position:fixed; inset:0; z-index:10; background:var(--bg);} }\n\t\t.card { border:1px solid var(--border); border-radius:8px; padding:10px 12px; margin:6px 0; cursor:pointer; }\n\t\t.card:hover{ border-color:var(--accent); }\n\t\t.badge { font-size:.75em; padding:1px 6px; border-radius:4px; background:var(--accent); color:#fff; }\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
